### ISSUE TITLE
During node creation getting error and SMN docker crash

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#22]
Filling up node configuration like in example and smn docker crash

see **docker logs smn**

`Warning: no saslprep library specified. Passwords will not be sanitized
Warning: no saslprep library specified. Passwords will not be sanitized
Warning: no saslprep library specified. Passwords will not be sanitized
events.js:167
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at /snapshot/smn/routes/index.js:0:0
    at Array.forEach (<anonymous>)
    at /snapshot/smn/routes/index.js:0:0
    at Model.$wrapCallback (/snapshot/smn/node_modules/mongoose/lib/model.js:4646:16)
    at /snapshot/smn/node_modules/mongoose/lib/query.js:4021:12
    at process.nextTick (/snapshot/smn/node_modules/mongoose/lib/helpers/query/completeMany.js:35:39)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at Model.$wrapCallback (/snapshot/smn/node_modules/mongoose/lib/model.js:4648:13)
    at /snapshot/smn/node_modules/mongoose/lib/query.js:4021:12
    at process.nextTick (/snapshot/smn/node_modules/mongoose/lib/helpers/query/completeMany.js:35:39)
    at process._tickCallback (internal/process/next_tick.js:61:11)
`
post to /wtcConfig looked like: wtcChainIpPort=http%3A%2F%2Fgwtc%3A6545&smnAccount=0xd98868e1d3736070deaf01a666271df9858110e7

**Comment by slklubaoding** [comment]
The possible reason for this is that Keystore file is incorrect. We have updated the version so users cannot add incorrect Keystores already. Let us know whether the issue reoccurs.Thank you for reporting this issue.

**Comment by slklubaoding** [comment]
We have received your feedback and are dealing with it
